name: vrm_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0+0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies:
  path: ^1.8.0
  json_annotation:

dev_dependencies:
  build_runner:
  json_serializable:
  lints: ^1.0.1
  test: ^1.18.2
